# .github/workflows/publish-to-pypi.yml
name: Publish Python 🐍 distributions to PyPI

on:
  push:
    branches:
      - master  # Or 'master', depending on your default branch name
    paths:
      - "pyproject.toml" # This is the key: the workflow only runs if the version file changes

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions to PyPI
    runs-on: ubuntu-latest
    
    # These permissions are required for Trusted Publishing (OIDC)
    permissions:
      id-token: write # This is essential for authentication with PyPI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
        
      - name: Build package
        run: python -m build
        # This will create the .tar.gz and .whl files in the 'dist/' directory

      - name: Publish package to PyPI
        # This action is the official one for publishing to PyPI
        # It will automatically use the OIDC token from the job permissions
        uses: pypa/gh-action-pypi-publish@release/v1
